import type { SyncEnvelope } from "./types";

export type SyncEntity =
  | "account" | "category" | "transaction" | "budget" | "investment";

export interface ChangeRow extends SyncEnvelope {
  entity: SyncEntity;
  [field: string]: unknown;
}

export interface ChangesPage {
  changes: ChangeRow[];
  /** Opaque "<revision>:<id>". Store it verbatim; do not parse or compare it. */
  nextCursor: string;
  hasMore: boolean;
}

export interface PushOp {
  /** One per mutation, generated by the client and never reused. This is what
   *  makes a retry after a timeout safe: the server applies it once. */
  opId: string;
  entity: SyncEntity;
  /** Client-generated (UUIDv7), so a row exists before the server sees it. */
  id: string;
  op: "upsert" | "delete";
  /** The revision the client was editing. Omit for a create. */
  baseRevision?: string | null;
  payload?: Record<string, unknown>;
}

export interface PushResult {
  applied: { opId: string; id: string; revision: string }[];
  conflicts: { opId: string; id: string; entity: string; reason: string }[];
  newRevision: string;
}

export interface Conflict {
  id: string;
  entity: string;
  entityId: string;
  losingPayload: Record<string, unknown>;
  winningRevision: string;
  createdAt: string;
}
